In [47]:
import numpy as np
from sklearn.datasets import load_digits
import matplotlib.pyplot as plt
from sklearn.cluster import KMeans
from sklearn.metrics import confusion_matrix
from sklearn.decomposition import PCA


In [48]:
digits = load_digits()

mu, sigma = 0, 1
noise = np.random.normal(mu, sigma, digits.data.shape)
noisy_digits = digits.data + noise


In [49]:
Kmeans_Noise = KMeans(n_clusters=10, random_state=42)
Kmeans_Noise.fit(noisy_digits)
labels_noisy = Kmeans_Noise.labels_
centers = Kmeans_Noise.cluster_centers_


/home/vraj/.local/lib/python3.8/site-packages/sklearn/cluster/_kmeans.py:870: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  warnings.warn(


In [50]:
accuracy = np.mean(labels_noisy == digits.target)
print("Accuracy:", accuracy*100, "%")

CM = confusion_matrix(labels_noisy, digits.target)
print("Confusion matrix:")
print(CM)


Accuracy: 6.844741235392321 %
Confusion matrix:
[[  0   0  14 159   0   1   0   0   4   7]
 [  0 100   9   7   2   0   2   2 106   0]
 [  1   0   0   0 163   1   0   1   0   0]
 [  0   0   2   6  11   0   0 167   3   8]
 [177   0   1   0   0   0   1   0   0   0]
 [  0  25 148   2   0   0   0   0   3   0]
 [  0   0   0   7   0  38   0   0  41 138]
 [  0   2   0   0   0   2 178   0   2   0]
 [  0  55   3   0   5   0   0   9  10  20]
 [  0   0   0   2   0 140   0   0   5   7]]


In [51]:
pca = PCA(n_components=2)
noisy_digits_pca = pca.fit_transform(noisy_digits)

Kmeans_Noise_PCA = KMeans(n_clusters=10, random_state=42)
Kmeans_Noise_PCA.fit(noisy_digits_pca)
labels_noisy_PCA = Kmeans_Noise_PCA.labels_
centers = Kmeans_Noise_PCA.cluster_centers_


/home/vraj/.local/lib/python3.8/site-packages/sklearn/cluster/_kmeans.py:870: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  warnings.warn(


In [52]:
accuracy = np.mean(labels_noisy_PCA == digits.target)
print("Accuracy:", accuracy*100, "%")

CM = confusion_matrix(labels_noisy_PCA, digits.target)
print("Confusion matrix:")
print(CM)


Accuracy: 16.30495269894268 %
Confusion matrix:
[[  0  89   2   0   2   2   0  34   6   0]
 [  8   6   3  21   0  51   0   0  11  76]
 [ 15   0   0   0  18   5 142   0   1   1]
 [  0   0 106  53   0   4   0   0   4   7]
 [  1   4   0   0 147   1  25   1   1   0]
 [  0  49  10   0  11  43   4  38  60  10]
 [  0   0   2  86   0   0   0   0   0  60]
 [154   0   0   0   0   5  10   0   0   0]
 [  0   5  16  13   3  27   0 105  27   9]
 [  0  29  38  10   0  44   0   1  64  17]]
